openapi: 3.0.0
info:
  title: Unofficial
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /api/classes/canceled:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: その月の最大10件のみ取得
                maxItems: 10
                items:
                  $ref: '#/components/schemas/CanceledClass'
      operationId: get-api-classes-canceled
      description: |-
        休講になったクラスの一覧を取得

        ※ページングなし
      requestBody: {}
  /api/classes/moved:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                maxItems: 10
                description: その月の最大10件のみ取得
                items:
                  $ref: '#/components/schemas/MovedClass'
      operationId: get-api-classes-moved
      description: |-
        移動になったクラスの一覧を取得

        ※ページングなし
  /api/classes/supplementary:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                maxItems: 10
                description: その月の最大10件のみ取得
                items:
                  $ref: '#/components/schemas/SupplementaryClass'
      operationId: get-api-classes-supplementary
      description: |-
        補講一覧を取得

        ※ページングなし
components:
  schemas:
    MovedClass:
      title: MovedClasswork
      type: object
      description: 日時が移動した授業
      properties:
        id:
          type: string
        before:
          type: object
          required:
            - className
            - date
            - periods
            - note
            - teacher
          properties:
            className:
              type: string
            date:
              type: string
              format: date
              description: YYYY-MM-DD
            periods:
              description: 時限
              type: array
              items:
                type: integer
            note:
              type: string
              description: 備考
            teacher:
              type: string
        after:
          type: object
          required:
            - className
            - date
            - periods
            - note
            - teacher
          properties:
            className:
              type: string
            date:
              type: string
              description: YYYY-MM-DD
            periods:
              type: array
              description: ''
              items:
                type: integer
            note:
              type: string
            teacher:
              type: string
        classNumber:
          description: 開講クラス
          type: object
          required:
            - grade
            - program
            - formerClass
            - regularCourse
            - note
          properties:
            grade:
              type: integer
              description: 学年
              minimum: 1
              maximum: 5
            program:
              type:
                - string
                - integer
              description: 系(1年は組)
              minLength: 1
              maxLength: 2
              minimum: 1
              maximum: 4
            formerClass:
              type: boolean
              description: 従来の科かどうか
            regularCourse:
              type: boolean
              description: 本科か専攻科か(本科ならtrue)
            note:
              type: string
              description: 留学生とか数学・物理科学プログラムみたいなの"
      required:
        - id
        - before
        - after
        - classNumber
    CanceledClass:
      title: CanceledClass
      type: object
      description: 休講になった授業
      properties:
        id:
          type: string
        className:
          type: string
          description: 授業名
        periods:
          description: 時限
          type: array
          items:
            type: integer
        date:
          type: string
          format: date
          description: YYYY-MM-DD
        teacher:
          type: string
        note:
          type: string
        classNumber:
          type: object
          required:
            - grade
            - program
            - formerClass
            - regularCourse
            - note
          properties:
            grade:
              type: integer
              description: 学年
              minimum: 1
              maximum: 5
            program:
              type:
                - string
                - integer
              description: 系(1年は組)
              minLength: 1
              maxLength: 2
              minimum: 1
              maximum: 4
            formerClass:
              type: boolean
              description: 従来の科かどうか
            regularCourse:
              type: boolean
              description: 本科か専攻科か(本科ならtrue)
            note:
              type: string
              description: 留学生とか数学・物理科学プログラムみたいなの"
      required:
        - id
        - className
        - periods
        - date
        - teacher
        - note
        - classNumber
    SupplementaryClass:
      title: SupplementaryClass
      type: object
      description: 補講
      properties:
        id:
          type: string
        className:
          type: string
        periods:
          type: array
          items:
            type: integer
        date:
          type: string
          format: date
          description: YYYY-MM-DD
        teacher:
          type: string
        note:
          type: string
        classNumber:
          type: object
          required:
            - grade
            - program
            - formerClass
            - regularCourse
            - note
          properties:
            grade:
              type: integer
              description: 学年
              minimum: 1
              maximum: 5
            program:
              type:
                - string
                - integer
              description: 系(1年は組)
              minLength: 1
              maxLength: 2
              minimum: 1
              maximum: 4
            formerClass:
              type: boolean
              description: 従来の科かどうか
            regularCourse:
              type: boolean
              description: 本科か専攻科か(本科ならtrue)
            note:
              type: string
              description: 留学生とか数学・物理科学プログラムみたいなの"
      required:
        - id
        - className
        - periods
        - date
        - teacher
        - note
        - classNumber
