openapi: 3.0.0
info:
  title: Unofficial
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /api/classes/canceled:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: 直近10件のみ取得 (系を選択が行われたら、その系の10件を取得)
                maxItems: 10
                items:
                  $ref: '#/components/schemas/CanceledClass'
      operationId: get-api-classes-canceled
      description: |-
        休講になったクラスの一覧を取得

        ※ページングなし
      requestBody: {}
  /api/classes/moved:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                maxItems: 10
                description: 直近10件のみ取得 (系を選択が行われたら、その系の10件を取得)
                items:
                  $ref: '#/components/schemas/MovedClass'
      operationId: get-api-classes-moved
      description: |-
        移動になったクラスの一覧を取得

        ※ページングなし
  /api/classes/supplymentaly:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                maxItems: 10
                description: 直近10件のみ取得 (系を選択が行われたら、その系の10件を取得)
                items:
                  $ref: '#/components/schemas/SupplymentalyClass'
      operationId: get-api-classes-supplymentaly
      description: |-
        補講一覧を取得

        ※ページングなし
components:
  schemas:
    MovedClass:
      title: MovedClasswork
      type: object
      description: 日時が移動した授業
      properties:
        id:
          type: string
        before:
          type: object
          required:
            - className
            - date
            - period
            - note
            - teacher
          properties:
            className:
              type: string
            date:
              type: string
              format: date
            period:
              type: string
              description: 時限
            note:
              type: string
              description: 備考
            teacher:
              type: string
        after:
          type: object
          required:
            - className
            - date
            - period
            - note
            - teacher
          properties:
            className:
              type: string
            date:
              type: string
            period:
              type: string
            note:
              type: string
            teacher:
              type: string
        classNumber:
          type: string
          description: 開講クラス
      required:
        - id
        - before
        - after
        - classNumber
    CanceledClass:
      title: CanceledClass
      type: object
      description: 休講になった授業
      properties:
        id:
          type: string
        className:
          type: string
          description: 授業名
        period:
          type: string
          description: 時限
        date:
          type: string
          format: date
        teacher:
          type: string
        note:
          type: string
      required:
        - id
        - className
        - period
        - date
        - teacher
        - note
    SupplymentalyClass:
      title: SupplymentalyClass
      type: object
      description: 補講
      properties:
        id:
          type: string
        className:
          type: string
        period:
          type: string
        date:
          type: string
        teacher:
          type: string
        note:
          type: string
      required:
        - id
        - className
        - period
        - date
        - teacher
        - note
